version: "3.5"

services:
  app:
    container_name: portfolio
    image: portfolio
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000